apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-healing-platform.fullname" . }}-backend
  namespace: {{ .Values.namespaceOverride }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "ai-healing-platform.name" . }}
    app.kubernetes.io/component: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 9000
      name: http

